import { Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { providerDisplayName, type AiResponseMeta } from "@/lib/ai/meta";

export function ProviderBadge({ meta, className }: { meta?: AiResponseMeta; className?: string }) {
  if (!meta?.provider && !meta?.model) return null;

  const label = meta.provider
    ? `Generated by ${providerDisplayName(meta.provider)}`
    : meta.model
      ? `Generated by ${meta.model}`
      : "Generated by AI";

  return (
    <Badge tone="accent" className={className}>
      <Sparkles size={11} />
      {label}
    </Badge>
  );
}
